title: Joe Mercer # your name (or website title) here
logo: "/images/Joe_Mercer.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Taking Data 
  <br><br>
  Creating Insights 
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-mercer-43413470/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-158951033-1 # your Google Analytics tracking ID here
